### PR TITLE
adding spanish to the `translate` languages

### PR DESCRIPTION
**Pull request by jposada202020**

### CODE REVIEW

**Comment by CedarGroveStudios** [comment]
Excellent. Thank you very much!

If possible I am inclined to name the file `english_to_espanol.py` and the internal dictionary `ENG_ESPANOL` to be consistent with the native language spelling of the existing translators. What do you think?

Also within the translation dictionary, do you think it would it be preferable to include the missing accent characters for `CALIBRACIÓN`, `ESPAÑOL`, `INVÁLIDO`, and `MÁXIMO`?

I appreciate your help with the translation. It will certainly help make the library more useful.

**Comment by jposada202020** [comment]
Hello, yes you are right and correct, the discussion if you need to to put accent in Capital letters is older than me... :)
https://www.rae.es/noticia/preguntas-frecuentes-tilde-en-las-mayusculas
I think I am just use not to.
I made the changes according to your recommendations. :)

PD wondering why my push did not change the file name... anyway you could do it in your side I guess...

**Comment by CedarGroveStudios** [comment]
Ah, I wasn't aware that accents on all caps had been debated. Good to know.

Again, thank you for the submission. I'll run the workflow and merge the changes (along with the filename change) later tonight. It'll be great to have Spanish added my portable quality tester.

**Comment by CedarGroveStudios** [comment]
There's an issue with the cookiecutter-generated Community Bundle CI, so I'll create a release using the source code from this pull request.

**Comment by jposada202020** [comment]
No worries, have a lot of trouble figuring out regarding the CI, last week. If there is anything I can do to help let me know.

**Comment by CedarGroveStudios** [comment]
Thanks for the offer to help; Git isn’t strongly represented in my vocabulary yet. @tekktrik is going to submit a PR to each of my Community Bundle source repos with the current library CI update. Hopefully that’ll do the trick.

**Comment by jposada202020** [comment]
LOL, it seems that you need ENG_GIT dictionary  as I do :)

**Comment by CedarGroveStudios** [comment]
> 

Indeed!

**Pull request closed without merging**
